In [1]:
import torch
import numpy as np
torch.__version__

'1.8.0a0+b50919b'

## 创建矩阵

In [6]:
# 直接创建矩阵
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [7]:
# 创建空/0矩阵 - 和 numpy 类似
np.empty((3,3)), torch.empty((3,3)), np.random.randn(3,3), torch.rand(3,3), torch.rand((3,3))

(array([[0.50338063, 0.0886115 , 0.62625911],
        [2.6745378 , 1.49680326, 0.93692592],
        [0.28605136, 1.10348178, 2.60348913]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 array([[ 1.30448465, -1.1991695 ,  0.83209718],
        [-0.40459409,  1.21164446, -0.45960217],
        [ 1.98995088, -0.54376153,  0.54379349]]),
 tensor([[0.1092, 0.7794, 0.5445],
         [0.3198, 0.0667, 0.2301],
         [0.6377, 0.8272, 0.9112]]),
 tensor([[0.9521, 0.2050, 0.9049],
         [0.6741, 0.1492, 0.7110],
         [0.6013, 0.7785, 0.1745]]))

In [11]:
# 直接创建常量tensor
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [12]:
# 从另外的tensor获得
x = torch.zeros((3,3))
torch.ones_like(x, dtype=torch.int8), torch.randn_like(x, dtype=torch.float32) # torch.dtype 查看类型

(tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]], dtype=torch.int8),
 tensor([[ 0.6613, -1.7398, -0.3245],
         [ 0.1812,  0.9102,  1.0807],
         [-0.7743,  0.1922,  0.0591]]))

In [9]:
# 从numpy转换
arr = np.array([1,2,3])
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 2, 3], dtype=torch.int32)

In [10]:
# torch类型转换为numpy类型
arr_torch.numpy()

array([1, 2, 3])

## tensor的属性

In [22]:
arr_torch = torch.full((3,3),3)
# 类型
tensor_type = arr_torch.dtype
# 设备
tensor_device = arr_torch.device
# shape
tensor_shape = arr_torch.shape # arr_torch.size()
# 查看维度
tensor_dim = arr_torch.dim()
tensor_type, tensor_device, tensor_shape, tensor_dim

(torch.int64, device(type='cpu'), torch.Size([3, 3]), 2)

## Scalar 形式
0维数组

In [18]:
# 取出0维度数组的数字
scalar =  torch.tensor(42)
scalar, scalar.item() # 注意：高维数组没有item()属性

(tensor(42), 42)

## 数组操作

### 索引和切片

In [24]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[...,-1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 连接

In [35]:
# torch.cat, torch.stack
tensor = torch.ones(2, 2)
tensor_cat_0 = torch.cat((tensor,tensor), dim=0)
tensor_stack_0 = torch.stack((tensor,tensor), dim=0)

tensor_cat_1 = torch.cat((tensor,tensor), dim=1)
tensor_stack_1 = torch.stack((tensor,tensor), dim=1)

tensor, tensor_cat_0, tensor_stack_0, tensor_cat_1, tensor_stack_1

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

### 改变形状

In [38]:
# 改变维度
tensor = torch.arange(9)
tensor.view((1,9)) # view
tensor.reshape((3,3)) # view

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [42]:
# 增加维度
print(tensor[:,None])
# 转换为1维度数组
tensor.flatten()
tensor.ravel()

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

### 更改数据类型

In [46]:
tensor = tensor.type(torch.int32) # 拷贝
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32)

In [49]:
tensor = tensor.long()  # 拷贝
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

## 数学运算

In [56]:
# 矩阵乘法
# tensor = torch.arange(4).reshape((2,2))
tensor = torch.ones(2,2)
y1 = tensor @ tensor
y2 = tensor.matmul(tensor)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor, out=y3)
y1, y2, y2

(tensor([[2., 2.],
         [2., 2.]]),
 tensor([[2., 2.],
         [2., 2.]]),
 tensor([[2., 2.],
         [2., 2.]]))

In [63]:
# 对应数字相乘
tensor = torch.ones(2,2)
y1 = tensor.mul(tensor)
y2 = torch.rand_like(y1)
torch.mul(tensor, tensor, out=y2)
y1, y2

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

## 与numpy的协同

In [64]:
# tensor -> numpy
t = torch.ones(5)
n = t.numpy() # 返回的是t的view()

print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [65]:
# tensor 和 numpy 相互影响
t.add_(1) # add_后面的横杠代表原位相加

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [69]:
# numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n,1,out=n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
