In [1]:
import torch
import numpy as np
torch.__version__

'1.8.0a0+b50919b'

## 创建矩阵

In [2]:
# 创建空/0矩阵
np.empty((3,3)), torch.empty((3,3)), np.random.randn(3,3), torch.rand(3,3)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 array([[ 0.47476786,  0.48442688, -0.93860956],
        [-1.00973914,  1.2346054 ,  1.85082098],
        [-0.29988736, -0.61755076,  1.37035593]]),
 tensor([[0.7041, 0.1913, 0.7053],
         [0.6719, 0.8334, 0.9139],
         [0.8065, 0.8379, 0.7031]]))

In [3]:
# 直接创建矩阵
torch.tensor([2,3],dtype=torch.float32)

tensor([2., 3.])

In [4]:
# ones_like, rand(n).like
x = torch.zeros((3,3))
torch.ones_like(x, dtype=torch.int8), torch.randn_like(x, dtype=torch.float32) # torch.dtype 查看类型

(tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]], dtype=torch.int8),
 tensor([[-1.7126,  0.8128,  2.9499],
         [-0.0360, -0.7212,  1.2173],
         [-0.1886, -0.1427,  2.0060]]))

# Scalar 形式
0维数组

In [5]:
scalar =  torch.tensor(42)

## 展示矩阵大小,改变维度

In [6]:
# 展示矩阵大小
x.size(),x.size()[0]  # np.shape

(torch.Size([3, 3]), 3)

In [7]:
# 查看维度
x.dim()

2

In [8]:
# x.item() # ValueError: only one element tensors can be converted to Python scalars
scalar.item()  # int(scalar.numpy())

42

In [9]:
# 改变维度
x.view((1,9)) # view
x.reshape((3,3)) # view

x.clone() # copy

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## 更改数据类型

In [12]:
x.type(torch.int32)

tensor([[0, 0, 0],
        [0, 1, 0],
        [2, 0, 0]], dtype=torch.int32)

In [14]:
x.long()

tensor([[0, 0, 0],
        [0, 1, 0],
        [2, 0, 0]])

## 与numpy的协同

In [10]:
# torch to numpy
x = torch.randn(3,3)
y = x.numpy()
y

array([[-0.88871485, -0.6527283 ,  0.03630412],
       [-0.6330581 ,  1.9641341 , -0.4026074 ],
       [ 2.4929228 , -0.1117723 ,  0.05388178]], dtype=float32)

In [11]:
# numpy to torch
x = torch.from_numpy(y)
x

tensor([[-0.8887, -0.6527,  0.0363],
        [-0.6331,  1.9641, -0.4026],
        [ 2.4929, -0.1118,  0.0539]])