In [50]:
import torch
import numpy as np
import torch.nn as nn

## 构建数据
10个数据，每个数据一个特征  
y = 2x+1

In [51]:
X_np = np.arange(10).reshape((-1,1))
X_np = X_np.astype(np.float32)
y_np = 2 * X_np + 1  + 0.1*np.random.randn(10,1) # 2*x+1 最后一项是随机抖动
y_np = y_np.astype(np.float32)
X_np,y_np

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]], dtype=float32),
 array([[ 0.96914285],
        [ 3.0682814 ],
        [ 4.8442483 ],
        [ 6.8623    ],
        [ 9.003161  ],
        [10.990907  ],
        [12.89527   ],
        [14.905873  ],
        [16.875662  ],
        [19.162106  ]], dtype=float32))

## 创建线性回归模型

In [52]:
# 创建类
class LR(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LR,self).__init__()
        self.linear = nn.Linear(input_dim, output_dim) # 输入层维度，输出层维度
    
    def forward(self,x):
        out = self.linear(x)
        return out

In [53]:
# 规定参数
X = torch.from_numpy(X_np).requires_grad_()
y = torch.from_numpy(y_np).requires_grad_()

input_dim = 1
output_dim = 1
model = LR(input_dim, output_dim)

epochs = 1000
lr = 0.01

# 优化器，传入参数和学习率，通过学习率和梯度对框架的w,b进行更新
optimizer = torch.optim.SGD(model.parameters(), lr =lr)

# 损失函数
criterion = nn.MSELoss()


In [54]:
# 训练
for epoch in range(epochs):
    epoch += 1
    # 梯度清零
    optimizer.zero_grad()

    # forward
    outputs = model.forward(X)
    
    # calculate loss
    loss = criterion(outputs, y)
    
    # backward
    loss.backward()

    # 更新权重参数 - # 不懂这里怎么传入梯度的 - 解决，tensor数组在反向传播时自带梯度，optimizer中传入了model.parameters()就可以知道梯度信息
    optimizer.step()
    
    if epoch % 50 == 0:
        print(f"epoch:{epoch},loss:{loss.item()}")

epoch:50,loss:0.05328069254755974
epoch:100,loss:0.03416590392589569
epoch:150,loss:0.02331623062491417
epoch:200,loss:0.017157942056655884
epoch:250,loss:0.013662363402545452
epoch:300,loss:0.011678317561745644
epoch:350,loss:0.010552125051617622
epoch:400,loss:0.009912851266562939
epoch:450,loss:0.009550091810524464
epoch:500,loss:0.009344116784632206
epoch:550,loss:0.009227229282259941
epoch:600,loss:0.009160916320979595
epoch:650,loss:0.009123238734900951
epoch:700,loss:0.009101895615458488
epoch:750,loss:0.009089763276278973
epoch:800,loss:0.00908287987112999
epoch:850,loss:0.009078972972929478
epoch:900,loss:0.00907673966139555
epoch:950,loss:0.009075479581952095
epoch:1000,loss:0.009074702858924866


In [55]:
# 预测结果
pred = model.forward(X).data.numpy()
pred

array([[ 0.93812793],
       [ 2.9425886 ],
       [ 4.947049  ],
       [ 6.95151   ],
       [ 8.95597   ],
       [10.96043   ],
       [12.964891  ],
       [14.969352  ],
       [16.973812  ],
       [18.978273  ]], dtype=float32)